### ISSUE TITLE
სიმულატორი, დასაწერი

### ISSUE THREAD

**Issue by Rshalika** [freeuni-sdp/iot-bath-humidity-sensor#1]
სიმულატორზე ერთად უნდა ვიმუშაოთ წესით. შევთანხმდეთ რაღაცებზე 

iot-bath-climate team here ,

**Comment by gosip** [comment]
iot-sim-bath-ში შევთანხმდეთ ჯობია, ვიდრე აქ. bathroom-ის სხვა გუნდებთანაც დავპოსტავ.
